import type { ItemDef } from "./types";

/**
 * Magaza esyalari. `stats` alanindaki degerler dogrudan sampiyonun
 * toplam degerlerine eklenir.
 */
export const ITEMS: ItemDef[] = [
  // ---------- Baslangic ----------
  {
    id: "dogger",
    name: "Uzun Kilic",
    cost: 350,
    emoji: "🗡️",
    color: "#e0603a",
    stats: { ad: 10 },
    desc: "+10 saldiri gucu",
    tags: ["ad"],
  },
  {
    id: "amulet",
    name: "Buyulu Tilsim",
    cost: 350,
    emoji: "🔮",
    color: "#7f6bff",
    stats: { ap: 18 },
    desc: "+18 yetenek gucu",
    tags: ["ap"],
  },
  {
    id: "ruby",
    name: "Yakut Kristal",
    cost: 400,
    emoji: "🔴",
    color: "#d8384a",
    stats: { maxHp: 180 },
    desc: "+180 can",
    tags: ["tank"],
  },
  {
    id: "cloth",
    name: "Zirh Yelegi",
    cost: 300,
    emoji: "🛡️",
    color: "#9fb3c8",
    stats: { armor: 18 },
    desc: "+18 zirh",
    tags: ["tank"],
  },
  {
    id: "null",
    name: "Buyu Pelerini",
    cost: 320,
    emoji: "🧿",
    color: "#5ad2c8",
    stats: { mr: 22 },
    desc: "+22 buyu direnci",
    tags: ["tank"],
  },

  // ---------- Cizmeler ----------
  {
    id: "boots1",
    name: "Hiz Cizmesi",
    cost: 300,
    emoji: "👢",
    color: "#8b6b4a",
    stats: { moveSpeed: 26 },
    desc: "+40 hareket hizi",
    unique: true,
    tags: ["boots"],
  },
  {
    id: "boots_ad",
    name: "Vahsi Pencesi",
    cost: 1000,
    emoji: "🥾",
    color: "#c2703c",
    stats: { moveSpeed: 35, attackSpeed: 0.35 },
    desc: "+55 hareket hizi, +%35 saldiri hizi",
    unique: true,
    tags: ["boots", "ad"],
  },
  {
    id: "boots_ap",
    name: "Buyulu Adimlar",
    cost: 1050,
    emoji: "🥿",
    color: "#8f7bff",
    stats: { moveSpeed: 35, magicPen: 14 },
    desc: "+55 hareket hizi, +14 buyu delici",
    unique: true,
    tags: ["boots", "ap"],
  },
  {
    id: "boots_tank",
    name: "Celik Pabuclar",
    cost: 1000,
    emoji: "🩴",
    color: "#9fb3c8",
    stats: { moveSpeed: 32, armor: 25, tenacity: 0.25 },
    desc: "+50 hareket hizi, +25 zirh, +%25 sarsilmazlik",
    unique: true,
    tags: ["boots", "tank"],
  },

  // ---------- Saldiri gucu ----------
  {
    id: "sword_inf",
    name: "Sonsuz Kilic",
    cost: 3200,
    emoji: "⚔️",
    color: "#ffb347",
    stats: { ad: 65, crit: 0.25 },
    desc: "+65 saldiri gucu, +%25 kritik sansi",
    tags: ["ad"],
  },
  {
    id: "bloodthirst",
    name: "Kan Icici",
    cost: 3100,
    emoji: "🩸",
    color: "#c0303f",
    stats: { ad: 55, lifesteal: 0.18 },
    desc: "+55 saldiri gucu, +%18 can calma",
    tags: ["ad"],
  },
  {
    id: "hydra",
    name: "Hidra Baltasi",
    cost: 3300,
    emoji: "🪓",
    color: "#c58b45",
    stats: { ad: 55, maxHp: 300, lifesteal: 0.08 },
    desc: "+55 saldiri gucu, +300 can, +%8 can calma",
    tags: ["ad"],
  },
  {
    id: "lastwhisper",
    name: "Son Fisilti",
    cost: 2900,
    emoji: "🏹",
    color: "#e0d0a0",
    stats: { ad: 40, armorPen: 28, attackSpeed: 0.15 },
    desc: "+40 saldiri gucu, +28 zirh delici",
    tags: ["ad"],
  },
  {
    id: "phantom",
    name: "Hayalet Dansi",
    cost: 2900,
    emoji: "💨",
    color: "#a8e6ff",
    stats: { attackSpeed: 0.55, crit: 0.2, moveSpeed: 16 },
    desc: "+%55 saldiri hizi, +%20 kritik, +25 hareket hizi",
    tags: ["ad"],
  },
  {
    id: "triforce",
    name: "Uclu Mizrak",
    cost: 3400,
    emoji: "🔱",
    color: "#ffd27a",
    stats: { ad: 35, maxHp: 280, attackSpeed: 0.3, abilityHaste: 20, moveSpeed: 13 },
    desc: "+35 SG, +280 can, +%30 saldiri hizi, +20 yetenek hizi",
    tags: ["ad"],
  },

  // ---------- Yetenek gucu ----------
  {
    id: "rabadon",
    name: "Olumcul Baslik",
    cost: 3600,
    emoji: "🎩",
    color: "#a06bff",
    stats: { ap: 130 },
    desc: "+130 yetenek gucu",
    tags: ["ap"],
  },
  {
    id: "voidstaff",
    name: "Bosluk Asasi",
    cost: 2800,
    emoji: "🪄",
    color: "#7a5cff",
    stats: { ap: 70, magicPen: 30 },
    desc: "+70 yetenek gucu, +30 buyu delici",
    tags: ["ap"],
  },
  {
    id: "hourglass",
    name: "Kum Saati",
    cost: 3000,
    emoji: "⏳",
    color: "#ffd27a",
    stats: { ap: 65, armor: 40 },
    desc: "+65 yetenek gucu, +40 zirh",
    tags: ["ap", "tank"],
  },
  {
    id: "liandry",
    name: "Azap Meshalesi",
    cost: 3100,
    emoji: "🔥",
    color: "#ff7a3c",
    stats: { ap: 75, maxHp: 320, abilityHaste: 15 },
    desc: "+75 yetenek gucu, +320 can, +15 yetenek hizi",
    tags: ["ap", "tank"],
  },
  {
    id: "luden",
    name: "Firtina Kuresi",
    cost: 3000,
    emoji: "⚡",
    color: "#6bc8ff",
    stats: { ap: 85, abilityHaste: 25, maxMp: 300 },
    desc: "+85 yetenek gucu, +25 yetenek hizi, +300 mana",
    tags: ["ap"],
  },

  // ---------- Dayaniklilik ----------
  {
    id: "sunfire",
    name: "Gunes Alevi",
    cost: 2900,
    emoji: "☀️",
    color: "#ffb03a",
    stats: { maxHp: 500, armor: 45 },
    desc: "+500 can, +45 zirh",
    tags: ["tank"],
  },
  {
    id: "spirit",
    name: "Ruh Zirhi",
    cost: 2800,
    emoji: "👻",
    color: "#7fe3d0",
    stats: { maxHp: 450, mr: 50, hpRegen: 6 },
    desc: "+450 can, +50 buyu direnci",
    tags: ["tank"],
  },
  {
    id: "warmog",
    name: "Dev Zirhi",
    cost: 3000,
    emoji: "🧱",
    color: "#c07f4a",
    stats: { maxHp: 850, hpRegen: 12 },
    desc: "+850 can, +12 can yenilenmesi",
    tags: ["tank"],
  },
  {
    id: "thornmail",
    name: "Dikenli Zirh",
    cost: 2700,
    emoji: "🌵",
    color: "#8fa46a",
    stats: { maxHp: 350, armor: 70 },
    desc: "+350 can, +70 zirh",
    tags: ["tank"],
  },

  // ---------- Destek ----------
  {
    id: "redemption",
    name: "Kefaret",
    cost: 2500,
    emoji: "🕊️",
    color: "#ffe9a8",
    stats: { maxHp: 300, hpRegen: 8, abilityHaste: 20, mpRegen: 6 },
    desc: "+300 can, +20 yetenek hizi, yenilenme",
    tags: ["support"],
  },
  {
    id: "ardent",
    name: "Ates Sansor",
    cost: 2400,
    emoji: "🪔",
    color: "#ffc06b",
    stats: { ap: 45, maxHp: 200, abilityHaste: 20, mpRegen: 8 },
    desc: "+45 yetenek gucu, +200 can, +20 yetenek hizi",
    tags: ["support", "ap"],
  },
];

export const ITEM_BY_ID = new Map(ITEMS.map((i) => [i.id, i]));

export function getItem(id: string): ItemDef | undefined {
  return ITEM_BY_ID.get(id);
}

export const MAX_ITEMS = 6;
